spin_manifest_version = 2

[application]
name = "tiny-server"
version = "0.1.0"
authors = ["efeijo <emanuell.feijo@gmail.com>"]
description = ""

[[trigger.http]]
route = "/..."
component = "tiny-server"

[component.tiny-server]
source = "main.wasm"
allowed_outbound_hosts = []
[component.tiny-server.build]
command = "tinygo build -target=wasi -gc=leaking -no-debug -o main.wasm main.go"
watch = ["**/*.go", "go.mod"]
